name: CI CD Practice

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker image build et
        run: docker build -t benim-nginx:test .

      - name: Container calistir
        run: docker run -d --name test-container -p 8080:80 benim-nginx:test

      - name: Uygulamayi test et
        run: |
          sleep 3
          curl -f http://localhost:8080

      - name: Docker Hub login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Image tagle
        run: docker tag benim-nginx:test ${{ secrets.DOCKERHUB_USERNAME }}/benim-nginx:latest

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/benim-nginx:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: SSH key hazirla
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: SSH host key ekle
        run: ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      - name: Server'a deploy et
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "docker pull baskaynak2001/benim-nginx:latest &&
             docker stop registry-test || true &&
             docker rm registry-test || true &&
             docker run -d --name registry-test -p 8084:80 baskaynak2001/benim-nginx:latest"
